dofile("/vibephone/require_shim.lua")
term.setBackgroundColor(colors.black)
term.setTextColor(colors.white)
term.clear()
term.setCursorPos(1,1)

print("Controller (local placeholder)")
print("Install/update Controller from App Store.")
print("")
print("Press any key...")
os.pullEvent("key")
